print('Hello world!')
print('Jak masz na imię?')
myName = input ()
print('Miło cię poznać,' + myName + '.')
print('Liczba słów w twoim imieniu wynosi:')
print(len(myName))
print('Ile masz lat?')
myAge = input()
print('Za rok będziesz mieć ' + str(int(myAge) + 1) + ' lat.')

